# Simulation Exercises

#### 1. How likely is it that you roll doubles when rolling two dice?
Probability of doubles = 0.1682



In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(52)

In [4]:
## Set the number of trials

n_trials = 10_000
n_rows = 10_000

## Roll two dice

n_dice = 2
n_cols = 2

# Use np's random choice
# Select from [1,2,3,4,5,6]

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(n_rows, n_cols)


rolls

array([[6, 5],
       [4, 6],
       [5, 1],
       ...,
       [3, 6],
       [5, 3],
       [6, 3]])

In [7]:
# programmatically recognize doubles:
doubles = []

for row in rolls:
    if row [0] == row [1]:
        doubles.append(row)
        
doubles

[array([4, 4]),
 array([6, 6]),
 array([5, 5]),
 array([2, 2]),
 array([2, 2]),
 array([2, 2]),
 array([5, 5]),
 array([5, 5]),
 array([4, 4]),
 array([1, 1]),
 array([1, 1]),
 array([4, 4]),
 array([2, 2]),
 array([1, 1]),
 array([1, 1]),
 array([2, 2]),
 array([6, 6]),
 array([1, 1]),
 array([6, 6]),
 array([2, 2]),
 array([1, 1]),
 array([6, 6]),
 array([5, 5]),
 array([5, 5]),
 array([2, 2]),
 array([1, 1]),
 array([6, 6]),
 array([2, 2]),
 array([1, 1]),
 array([3, 3]),
 array([6, 6]),
 array([3, 3]),
 array([1, 1]),
 array([5, 5]),
 array([5, 5]),
 array([1, 1]),
 array([4, 4]),
 array([3, 3]),
 array([6, 6]),
 array([1, 1]),
 array([4, 4]),
 array([3, 3]),
 array([3, 3]),
 array([6, 6]),
 array([2, 2]),
 array([5, 5]),
 array([6, 6]),
 array([4, 4]),
 array([6, 6]),
 array([1, 1]),
 array([3, 3]),
 array([5, 5]),
 array([2, 2]),
 array([6, 6]),
 array([5, 5]),
 array([6, 6]),
 array([2, 2]),
 array([4, 4]),
 array([3, 3]),
 array([4, 4]),
 array([1, 1]),
 array([5, 5]),
 array([

In [9]:
num_dubbs = len(doubles)
num_dubbs

1682

In [11]:
percent_dubbs = num_dubbs / len(rolls)
percent_dubbs

0.1682

In [13]:
rolls_df = pd.DataFrame(rolls)

In [14]:
rolls_df.head()

0  1
0  6  5
1  4  6
2  5  1
3  6  3
4  4  4

In [18]:
# the easy way
dubb_bool = rolls_df[0]==rolls_df[1] 

prop_dubbs_df = dubb_bool.mean()

prop_dubbs_df

In [20]:
prop_dubbs_df = dubb_bool.mean()

In [21]:
prop_dubbs_df

0.1682

#### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

Exactly 3 = 0.2142
More than 3 = 0.6387

In [24]:
heads = True
tails = False
p_heads = p_tails = 0.5

n2_rows = 10_000
n2_cols = 8

flips_a = np.random.choice([heads, tails], size=(n2_rows, n2_cols))
flips_a

array([[False, False, False, ..., False,  True, False],
       [False,  True,  True, ...,  True, False,  True],
       [ True,  True, False, ..., False,  True, False],
       ...,
       [False, False,  True, ...,  True, False, False],
       [ True, False,  True, ..., False, False,  True],
       [False, False,  True, ..., False,  True,  True]])

In [25]:
flips = pd.DataFrame(flips_a)

In [27]:
flips.head()

0      1      2      3      4      5      6      7
0  False  False  False  False  False  False   True  False
1  False   True   True   True  False   True  False   True
2   True   True  False  False  False  False   True  False
3  False   True  False   True  False  False   True   True
4  False   True   True  False   True  False   True   True

In [29]:
exactly_3 = flips.sum(axis=1) == 3
exactly_3.head()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [30]:
prob_exactly_3 = exactly_3.mean()
prob_exactly_3

0.2142

In [32]:
more_than_3 = flips.sum(axis=1) > 3
more_than_3.head(3)

0    False
1     True
2    False
dtype: bool

In [33]:
more_than_3.mean()

0.6387

#### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

Theoretical prob of two data science students on billboards = 0.0625

Model prob of two data science students on billboards = 0.0673



In [111]:
# two billboards = columns
# rows = number of trials
# possible outcomes = (a data science student (1/4 chance), 
    # a web dev student (3/4 chance))

n3_cols = 2
n3_rows = 10_000

prob_web_dev = .75
prob_ds = .25

billboards_a = np.random.choice(
    ['wd', 'ds'], p=[prob_web_dev, prob_ds], size=(n3_rows, n3_cols)) 
billboards_a


array([['wd', 'wd'],
       ['ds', 'ds'],
       ['wd', 'wd'],
       ...,
       ['ds', 'ds'],
       ['wd', 'ds'],
       ['ds', 'wd']], dtype='<U2')

In [112]:
billboards = pd.DataFrame(billboards_a)
billboards.head(3)

0   1
0  wd  wd
1  ds  ds
2  wd  wd

In [113]:
two_ds_bools = (billboards[0]=='ds') & (billboards[1]=='ds')
two_ds_bools

0       False
1        True
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997     True
9998    False
9999    False
Length: 10000, dtype: bool

In [114]:
prob_2_ds = two_ds_bools.mean()
prob_2_ds

0.0657

#### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values
Probability of a package of Poptarts left Friday afternoon = 0.72447


In [118]:
pts_bought_per_week_bools

array([False, False,  True, ..., False,  True, False])

In [119]:
n4_cols = 5  #days of week codeup is open
n4_rows = 100_000  #number of trials to run

# generate array of normally distributed values based on daily avg sales and std
pts_bought_per_week_a = np.random.normal(loc=3, scale=1.5, size=(n4_rows, n4_cols))
pts_bought_per_week_a

# convert to df
pts_bought_per_week = pd.DataFrame(pts_bought_per_week_a)
pts_bought_per_week.head()

# adjust for friday mid-afternoon (.75 day?):
pts_bought_per_week[4] = pts_bought_per_week[4] * .75
pts_bought_per_week

# compare sum of poptarts sold up to friday mid-pm with number stocked for week.
pts_bought_per_week_bools = (pts_bought_per_week_a.sum(axis=1) - 17) > 0
pts_bought_per_week_bools

# convert the bools to a probability:
prob_no_pts_fri_pm = 1 - pts_bought_per_week_bools.mean()
prob_no_pts_fri_pm

0.72447

In [116]:
np.random.normal(loc=3, scale=1.5, size=(n4_rows, n4_cols))

array([[ 4.09740848,  2.37805313,  4.77695377,  2.43879915,  2.24154337],
       [ 1.22289002,  3.78965816,  3.57386962,  0.93958688,  0.73679462],
       [ 2.74019688, -0.58199543,  1.61661124,  1.16787876,  1.43578247],
       ...,
       [ 1.68877318,  3.6865635 ,  0.39611937,  3.32845494,  2.91948536],
       [ 3.42125692,  2.89040654,  4.13641103,  4.34909951,  1.06138224],
       [ 3.97094266,  4.3871636 ,  2.29855855,  5.13211503,  4.1808166 ]])

#### 5. Compare Heights
- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?
Modeled probability that random woman is taller than random man 0.2058


In [95]:
# number of sample pairs we want to generate
n5_rows = 10_000  

# one random man's height based on given mu and sigma
# one random woman's height based on given mu and sigma
m = pd.DataFrame(np.random.normal(loc=178, scale=8, size =(n5_rows, 1)))
w = pd.DataFrame(np.random.normal(loc=170, scale=6, size =(n5_rows, 1)))

# compare the two values across the two DataFrames:
bools = w > m
bools
prob_woman_taller = bools.mean()
prob_woman_taller

0    0.2058
dtype: float64

#### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students? 
No failures after 50 students = 0.8173
No failures after 100 students = 0.6766
#### What is the probability that we observe an installation issue within the first 150 students that download anaconda?
A failure in first 150 students = 0.4471
#### How likely is it that 450 students all download anaconda without an issue?
No failures after 450 students = 0.1686


In [106]:
# # number of sample pairs we want to generate
n6_rows = 10_000  

# chance of failure on a download 1/250
# we want to know about groups of 50 downloads
n6_cols = 450

works = True
fails = False

# generate random sets of 50 downloads:
sets_of_downloads_a = np.random.choice(
    [works, fails], size = (n6_rows, n6_cols), p=[(249/250), (1/250)])

# convert to DataFrame
sets_of_downloads = pd.DataFrame(sets_of_downloads_a)

no_failures_bools = (sets_of_downloads.sum(axis=1) == n6_cols)
no_failures_bools.mean()
# a_failure = 1 - no_failures_bools.mean()
# a_failure

0.1686

#### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?
#### How likely is it that a food truck will show up sometime this week?



In [139]:
# What are the outcomes?
#0 - no truck
#1 - truck is present

trucks = np.random.choice([0, 1], size = (10000, 3), p = [0.3, 0.7])
#probability that no truck shows up
(trucks.sum(axis = 1) == 0).mean()

0.026

In [142]:
# truck shows up at least once.
(trucks.sum(axis = 1) >= 1).mean()

0.974

In [155]:
# Food truck shows up at least once in a week
weekly_trucks = np.random.choice([0, 1], size = (10000, 7), p = [0.3, 0.7])
(weekly_trucks.sum(axis=1) > 0).mean()

0.9997

#### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?
23 people = 0.36639
20 people = 0.32414
40 people = 0.26043
These numbers are for exactly 2 people sharing a birthday, which explains why the probability goes down for 40 people.



In [138]:
num_people_in_room = 40   # columns
num_possible_birthdays = 366  # range of outcomes
num_trials = 10**5 # rows

birthday_sets_a = np.random.choice(
    range(1, 367), size = (num_trials, num_people_in_room))
birthday_sets = pd.DataFrame(birthday_sets_a)
birthday_sets
two_share_bday = (birthday_sets.nunique(axis=1) == (num_people_in_room - 1))
two_share_bday
p_two_share_bday = two_share_bday.mean()
p_two_share_bday

0.26043